# https://www.mkdocs.org/user-guide/configuration/

# Project information
site_name: 'AWS Sync Routes'
site_description: 'Synchronizes the specified route from the main/default route table to all custom route tables in the VPC.'
site_author: 'Amazon Web Services, Inc.'
site_url: 'https://awslabs.github.io/aws-sync-routes/'

# Repository
repo_name: 'aws-sync-routes'
repo_url: 'https://github.com/awslabs/aws-sync-routes'
remote_branch: 'gh-pages'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  custom_dir: 'material'

  # 404 page
  static_templates:
    - '404.html'

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Theme
  language: 'en'
  feature:
    tabs: false
  palette:
    primary: 'smile'
    accent: 'dark-orange'
  font: false
  logo:
    icon:
      'home'

# Customization
extra:
  manifest: 'manifest.json'
  social:
    - type: 'globe'
      link: 'https://aws.amazon.com/'
    - type: 'github-alt'
      link: 'https://github.com/awslabs/aws-sync-routes'
    - type: 'twitter'
      link: 'https://twitter.com/AWSOpen'
    - type: 'reddit-alien'
      link: 'https://www.reddit.com/r/aws/'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Getting Started: 'index.md'
  - Architecture Decision Records:
    - Record architecture decisions: 'adr/0001-record-architecture-decisions.md'
    - AWS Amplify CLI toolchain: 'adr/0002-aws-amplify-cli-toolchain.md'
    - HTTP PATCH method: 'adr/0003-http-patch-method.md'
    - API Key: 'adr/0004-api-key.md'
    - URI: 'adr/0005-uri.md'
    - Specificity: 'adr/0006-specificity.md'
  - About:
    - Contributing Guidelines: 'about/contributing.md'
    - License: 'about/license.md'
